//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetBookAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class address_details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public address_details()
        {
            this.clinic_profile = new HashSet<clinic_profile>();
        }
    
        public string Id { get; set; }
        public string Country { get; set; }
        public string City { get; set; }
        public string Barangay { get; set; }
        public string Line { get; set; }
    
        public virtual owner_profile owner_profile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<clinic_profile> clinic_profile { get; set; }
    }
}
