//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetBookAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class clinic_profile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public clinic_profile()
        {
            this.contact_numbers = new HashSet<contact_numbers>();
        }
    
        public string Id { get; set; }
        public string Name { get; set; }
        public string AddressId { get; set; }
        public string VetFirstName { get; set; }
        public string VetMiddleName { get; set; }
        public string VetLastName { get; set; }
    
        public virtual address_details address_details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<contact_numbers> contact_numbers { get; set; }
    }
}
