//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetBookAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PetBookEntities : DbContext
    {
        public PetBookEntities()
            : base("name=PetBookEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<account_credential> account_credential { get; set; }
        public virtual DbSet<account_type> account_type { get; set; }
        public virtual DbSet<address_details> address_details { get; set; }
        public virtual DbSet<allergen> allergens { get; set; }
        public virtual DbSet<clinic_profile> clinic_profile { get; set; }
        public virtual DbSet<clinic_review> clinic_review { get; set; }
        public virtual DbSet<file_types> file_types { get; set; }
        public virtual DbSet<full_names> full_names { get; set; }
        public virtual DbSet<media_files> media_files { get; set; }
        public virtual DbSet<medical_record> medical_record { get; set; }
        public virtual DbSet<mobile_numbers> mobile_numbers { get; set; }
        public virtual DbSet<owner_profile> owner_profile { get; set; }
        public virtual DbSet<pet_profile> pet_profile { get; set; }
        public virtual DbSet<post_media_files> post_media_files { get; set; }
        public virtual DbSet<profile_picture> profile_picture { get; set; }
        public virtual DbSet<profile_post> profile_post { get; set; }
        public virtual DbSet<profile_post_comment> profile_post_comment { get; set; }
        public virtual DbSet<profile_post_like> profile_post_like { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<vaccine_names> vaccine_names { get; set; }
        public virtual DbSet<vaccine_types> vaccine_types { get; set; }
        public virtual DbSet<contact_numbers> contact_numbers { get; set; }
        public virtual DbSet<login_sessions> login_sessions { get; set; }
        public virtual DbSet<pet_antiparasitic> pet_antiparasitic { get; set; }
        public virtual DbSet<pet_color> pet_color { get; set; }
        public virtual DbSet<pet_vaccines> pet_vaccines { get; set; }
    }
}
